from datetime import datetime, timezone
from typing import Any
from pydantic import BaseModel, Field

class GeneratedProperty(BaseModel):
    """Monitoring property generated by an LLM."""

    task_id: str = Field(
        ...,
        description="Identifier of the task that produced this property.",
    )

    xml: str = Field(
        ...,
        description="Generated MMT XML property.",
    )

    model: str = Field(
        ...,
        description="LLM used to generate the property.",
    )

    attempt: int = Field(
        default=1,
        ge=1,
        description="Generation or repair attempt number.",
    )

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
    )